/**
 * Universidad de La Laguna
 * Escuela Superior de Ingeniería y Tecnología
 * Grado en Ingeniería Informática
 * Programación de Aplicaciones Interactivas
 * @author Adrián Pérez Poleo
 * @since Apr 25, 2026
 * @desc ENumeration of countries in spanish.
 */

export enum CountryNamesInSpanish {
  AFGANISTAN = 'AFGANISTAN',
  ALEMANIA = 'ALEMANIA',
  ANTIGUA = 'ANTIGUA Y BARBUDA',
  ARGELIA = 'ARGELIA',
  ARGENTINA = 'ARGENTINA',
  AUSTRALIA = 'AUSTRALIA',
  AUSTRIA = 'AUSTRIA',
  BELGICA = 'BELGICA',
  BOLIVIA = 'BOLIVIA',
  BOSNIA = 'BOSNIA Y HERZEGOVINA',
  BRASIL = 'BRASIL',
  CAMERUN = 'CAMERUN',
  CANADA = 'CANADA',
  CHILE = 'CHILE',
  COLOMBIA = 'COLOMBIA',
  CROACIA = 'CROACIA',
  CUBA = 'CUBA',
  DINAMARCA = 'DINAMARCA',
  ECUADOR = 'ECUADOR',
  EGIPTO = 'EGIPTO',
  ESPANA = 'ESPAÑA',
  ESTADOS_UNIDOS = 'ESTADOS UNIDOS',
  FILIPINAS = 'FILIPINAS',
  FINLANDIA = 'FINLANDIA',
  FRANCIA = 'FRANCIA',
  GRAN_BRETANA = 'GRAN BRETAÑA',
  GRECIA = 'GRECIA',
  GUATEMALA = 'GUATEMALA',
  HONDURAS = 'HONDURAS',
  INDIA = 'INDIA',
  INGLATERRA = 'INGLATERRA',
  IRLANDA = 'IRLANDA',
  ITALIA = 'ITALIA',
  JAPON = 'JAPON',
  LETONIA = 'LETONIA',
  LUXEMBURGO = 'LUXEMBURGO',
  MARRUECOS = 'MARRUECOS',
  MEXICO = 'MEXICO',
  NICARAGUA = 'NICARAGUA',
  NORUEGA = 'NORUEGA',
  PANAMA = 'PANAMA',
  PARAGUAY = 'PARAGUAY',
  PERU = 'PERU',
  POLONIA = 'POLONIA',
  PORTUGAL = 'PORTUGAL',
  PUERTO_RICO = 'PUERTO RICO',
  RUMANIA = 'RUMANIA',
  RUSIA = 'RUSIA',
  SENEGAL = 'SENEGAL',
  SUECIA = 'SUECIA',
  SUIZA = 'SUIZA',
  URUGUAY = 'URUGUAY',
  UZBEKISTAN = 'UZBEKISTAN',
  VENEZUELA = 'VENEZUELA'
}